-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 19:06:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sos` ;

-- -----------------------------------------------------
-- Schema sos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sos` DEFAULT CHARACTER SET utf8 ;
USE `sos` ;

-- -----------------------------------------------------
-- Table `sos`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sos`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sos`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS sistema;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'sistema' IDENTIFIED BY '505c0v1d';

GRANT SELECT ON TABLE `sos`.* TO 'sistema';
GRANT SELECT, INSERT, TRIGGER ON TABLE `sos`.* TO 'sistema';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `sos`.* TO 'sistema';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
